### ISSUE TITLE
Comment in DisplayTrajectory is too long

### ISSUE THREAD

**Issue by PeterMitrano** [ros-planning/moveit_msgs#115]
See the text overflowing at
http://docs.ros.org/en/melodic/api/moveit_msgs/html/msg/DisplayTrajectory.html

This is super low hanging fruit. We should also remember to backport to at least melodic.

The file that needs fixing is https://github.com/ros-planning/moveit_msgs/blob/master/msg/DisplayTrajectory.msg

**Comment by v4hn** [comment]
Where is your PR if this is "super low hanging" ;)
I could have clicked "merge" by now. :smile_cat:
