### ISSUE TITLE
PositionIKRequest has no member named attempts

### ISSUE THREAD

**Issue by robberthofmanfm** [ros-planning/moveit_msgs#138]
Hello there,

I am trying to get a workspace that was written for melodic running on noetic. I've encountered the following error:

 `error: ‘moveit_msgs::PositionIKRequest’ {aka ‘struct moveit_msgs::PositionIKRequest_<std::allocator<void> >’} has no member named ‘attempts’`

Apparently, https://github.com/ros-planning/moveit_msgs/commit/82cda0ee22a06965bceb93ab0228a0cedbbd29eb removed that field.
Why?

**Comment by robberthofmanfm** [comment]
Ah, seems like I have missed PR https://github.com/ros-planning/moveit_msgs/pull/76

**Comment by JafarAbdi** [comment]
Hi @robberthofmanfm,

See https://github.com/ros-planning/moveit/pull/1288 for why it was changed & https://github.com/ros-planning/moveit/blob/master/MIGRATION.md#ros-melodic for how to migrate your kinematics.yaml
