### ISSUE TITLE
Not clear if `orientation_constraint.absolute_x_axis_tolerance` is +/- or total tolerance

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit_msgs#140]
For example, is this:

orientation_constraint.absolute_x_axis_tolerance = 0.4;

+/- 0.4 rad?
Or +/- 0.2 rad?

**Comment by AndyZe** [comment]
Per comment here, it is +/- 0.2 rad:  https://github.com/ros-planning/moveit2/pull/1273

> * - absolute_x_axis_tolerance / 2 < error[0] < absolute_x_axis_tolerance / 2

**Comment by mamoll** [comment]
Fixed by PR #141
