### ISSUE TITLE
remove GetKinematicSolverInfo.srv

### ISSUE THREAD

**Issue by isucan** [ros-planning/moveit_msgs#3]
It is only used by pr2_arm_kinematics and nobody calls it. With the new plugin API for kinematics, this is not needed and causes confusion.

**Comment by 130s** [comment]
Addressed for Kinetic in https://github.com/ros-planning/moveit_msgs/pull/35

**Comment by 130s** [comment]
> Addressed for Kinetic in https://github.com/ros-planning/moveit_msgs/pull/35

That's only for ROS Kinetic onward, so reopening.

**Comment by davetcoleman** [comment]
No, I don't think we should backport a change like this to LTS indigo, or even jade. This issue has been addressed and can be closed.

**Comment by k-okada** [comment]
we could not compile pr2_apps on kinetic due to this change, so how can we rewrite the code without using GetKinematicSolverInfo
see https://github.com/PR2/pr2_apps/pull/35

**Comment by v4hn** [comment]
@k-okada The most convenient way to get the same list of joints is probably
```
moveit::planning_interface::MoveGroupInterface left("left_arm");
std::vector<std::string> joint_names= left.getActiveJoints();
```

Maybe you want to use `getJointNames()` instead.
I'm not sure whether the old service listed passive/mimic joints or not.
For the specific use-case on the PR2's arm groups this shouldn't matter though.
