### ISSUE TITLE
Release moveit_msgs (Indigo 0.7.5, Kinetic 0.9.x)

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit_msgs#33]
My local build broke because I was only using moveit_msgs from shadow-fixed, which is missing https://github.com/ros-planning/moveit_msgs/commit/4eb711cd2c5b764bee7bac3d7db8fec82d16132e

@130s thanks!

**Comment by davetcoleman** [comment]
Note: https://github.com/ros-planning/moveit_msgs/issues/34

**Comment by 130s** [comment]
I https://github.com/ros/rosdistro/pull/13218
J https://github.com/ros/rosdistro/pull/13219
For K I wait for a confirmation following https://github.com/ros-planning/moveit_msgs/pull/35#issuecomment-260755046.

**Comment by davetcoleman** [comment]
Ready to release kinetic

**Comment by 130s** [comment]
Ok, 
K https://github.com/ros/rosdistro/pull/13221
