### ISSUE TITLE
Move some other *_msgs packages into moveit_msgs repo

### ISSUE THREAD

**Issue by 130s** [ros-planning/moveit_msgs#39]
[household_objects_database_msgs](https://github.com/ros-interactive-manipulation/household_objects_database_msgs) and [manipulation_msgs](https://github.com/ros-interactive-manipulation/manipulation_msgs) are dependended by MoveIt! AFAIK. Both of those packages are maintained in a separate repo as a unary package, which duplicated the effort upon making a release. Since the primary usage of those packages *might* be MoveIt! these days, it makes sense to move them into MoveIt!-related repo and combine the maintenance effort.

Caveat is, all packages in a single repo needs to align the same version AFAIK. We can adjust to the highest available version as 0.9.x without any issue IMO.
- 0.1.2 household_objects_database_msgs
- 0.2.1 manipulation_msgs
- 0.9.1 (kinetic-devel) moveit_msgs

**Comment by v4hn** [comment]
Both packages are not (or at least should not be) dependencies of MoveIt kinetic+.
See https://github.com/ros-planning/moveit/commit/29564393260a8d5bac41eb036aedb282149fffa2
What makes you think we still need them? Did I miss something in the referenced commit?

**Comment by 130s** [comment]
No you didn't, you're right. I also left a comment at https://github.com/ros-interactive-manipulation/manipulation_msgs/issues/10#issuecomment-297100734 Closing as this is unnecessary.
