### ISSUE TITLE
remove GetConstraintAwarePositionIK.srv

### ISSUE THREAD

**Issue by isucan** [ros-planning/moveit_msgs#4]
It does not make sense to me to have two almost identical services. I have added a flag for collision checking and a Constraints message to the regular IK request (this costs just a few bytes (i believe 8 bytes) in the request) and an if statement in the implementation. It makes life easier for implementing things and also to call things.
The only code that uses that service is kinematics_constraint_aware

**Comment by 130s** [comment]
Addressed for Kinetic in https://github.com/ros-planning/moveit_msgs/pull/35

**Comment by davetcoleman** [comment]
Only took 3 years :hourglass_flowing_sand:
