### ISSUE TITLE
Any plan for the noetic release

### ISSUE THREAD

**Issue by JaehyunShim** [ros-planning/moveit_msgs#86]
Hi, 

It seems this repository hasn't been released for the noetic version yet.
Any concrete plans for it?

Ryan

**Comment by tylerjw** [comment]
Hello Ryan,

I'm planning on working on this today.  I'm going to create a noetic-devel branch and release that unless there are objections.

**Comment by v4hn** [comment]
Do you need to split from `master`? For the main repo we did not want to split yet, though [we do have a preliminary branch](https://github.com/ros-planning/moveit/issues/2253) already.

**Comment by v4hn** [comment]
It might make sense to merge #58 and fix the corresponding pr in moveit general before releasing the messages, but I will not spend time on this. Nor did anyone else consider it worthwhile to work on it for quite a long time.

**Comment by tylerjw** [comment]
Good point.  I didn't understand the reason for the noetic-devel branch on moveit.  I am in favor of just releasing Noetic on master.  I can look into that issue to see if I can get that finished quickly.  I don't remember what is blocking it.

**Comment by tylerjw** [comment]
@v4hn [It doesn't look like we think the approach to the issue you linked is the correct solution.](https://github.com/ros-planning/moveit/pull/1710#issuecomment-557538087)

That being said there will always be changes in flight.  I think we should release Noetic and accept that we can release it again in some time with some breaking changes.  

Noetic is the last ROS1 release so we can no longer rely on future ROS1 releases to provide opportunity for breaking changes and will just have to deal with and accept that that will be a part of the releases unless we just choose not to release any more.  We should be able to use version changes to enable people to use the old version if that is what they want.

**Comment by v4hn** [comment]
moveit's `noetic-devel` branch is currently @rhaschke's personal playground. Nothing to resolve there really. :-)

**Comment by tylerjw** [comment]
> moveit's `noetic-devel` branch is currently @rhaschke's personal playground. Nothing to resolve there really. :-)

I realize that now, it just confused me.

**Comment by v4hn** [comment]
> Noetic is the last ROS1 release so we can no longer rely on future ROS1 releases to provide opportunity for breaking changes and will just have to deal with and accept that that will be a part of the releases unless we just choose not to release any more. We should be able to use version changes to enable people to use the old version if that is what they want.

With this thought in might, it seems a very good idea to add SONAMES to all moveit-related repositories which do not have them already! That's probably not relevant for this repository though.

**Comment by tylerjw** [comment]
What do you mean you mean by adding SONAMES?  I'm sorry, I don't follow.

**Comment by v4hn** [comment]
https://github.com/ros-planning/moveit/pull/383 and https://github.com/ros-planning/geometric_shapes/issues/146 for reference.

**Comment by tylerjw** [comment]
Reading about SONAME and that it is the standard way to do backwards-incompatible releases of library binaries in linux... How would we go about that for a messages repo?

**Comment by v4hn** [comment]
On Wed, Aug 19, 2020 at 08:01:47AM -0700, Tyler Weaver wrote:
> Reading about SONAME and that it is the standard way to do backwards-incompatible releases of library binaries in linux... How would we go about that for a messages repo?

As I said, it's not relevant for *this* particular repository. But for pretty much all other moveit-dependencies you plan to release soon. :-)

**Comment by tylerjw** [comment]
Do you know why `0.7.3` was the binary version that was used in moveit?

**Comment by v4hn** [comment]
Please look at the links above again.

I only hardcoded 0.7.3 (as the MoveIt version in that branch back then) in `indigo-devel`.
`master` currently changes sonames *with each release*.
While this is not ideal, it means we don't have to bother with detailed ABI checks during releases.

**Comment by tylerjw** [comment]
Ok, I'll go around and create PRs for any repo that doesn't have this (also need to validate that all the projects in moveit itself have these).

**Comment by tylerjw** [comment]
Here is the SONAME change for geometric_shapes: https://github.com/ros-planning/geometric_shapes/pull/157

**Comment by tylerjw** [comment]
This is released for Noetic, closing.
