### ISSUE TITLE
Noetic Release (0.11.1)

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit_msgs#92]
# MoveIt Noetic Release (0.11.1)

[_moveit.ros.org release documentation_](https://moveit.ros.org/documentation/contributing/releases/)

### Checklist
- [x] Update changelogs
- [x] Bloom

**Comment by tylerjw** [comment]
https://github.com/ros/rosdistro/pull/26887

**Comment by machinekoder** [comment]
@tylerjw Shouldn't it be closed?

**Comment by tylerjw** [comment]
Yes, thankyou for pointing that out.  Here is it on ros index: https://index.ros.org/p/moveit_msgs/#noetic
